export const dataIntro = (): string => {
    return `Trường Đại học Kinh tế – Kỹ thuật Công nghiệp được thành lập theo Quyết định số 1206/QĐ-TTg ngày 11 tháng 9 năm 2007 của Thủ tướng Chính phủ, trên cơ sở nâng cấp Trường Cao đẳng Kinh tế Kỹ thuật Công nghiệp I, tiền thân là Trường Trung cấp Kỹ thuật III, được thành lập năm 1956. Trải qua hơn nửa thế kỷ, tập thể lãnh đạo, cán bộ, giáo viên, công nhân, viên chức và học sinh sinh viên của Nhà trường đã bền bỉ phấn đấu, tập trung trí tuệ và sáng tạo, vượt qua mọi khó khăn thử thách để đưa Nhà trường liên tục phát triển bền vững với những thành tích vẻ vang trong sự nghiệp đào tạo, phát triển nguồn nhân lực cho đất nước.

    Để có được những thành quả to lớn của ngày hôm nay, chúng ta không quên nhớ về cội nguồn. Đó là truyền thống 60 năm xây dựng và phát triển.
    
    QUÁ TRÌNH PHÁT TRIỂN CỦA NHÀ TRƯỜNG ĐƯỢC KHÁI QUÁT THEO 3 GIAI ĐOẠN
    
    GIAI ĐOẠN 1
    
    40 năm đào tạo bậc trung học chuyên nghiệp
    
    Ngay từ năm 1956, sau thời kỳ cải tạo XHCN, đất nước bước vào công cuộc khôi phục phát triển kinh tế ở miền Bắc và đấu tranh giải phóng miền Nam, Đảng và Nhà nước ta đã củng cố và phát triển giáo dục, đào tạo, với việc thành lập hệ thống các trường đại học, trung học chuyên nghiệp và dạy nghề. Trường Trung cấp Kỹ thuật III là một trong số những trường THCN được thành lập trong thời kỳ đó, với nhiệm vụ đào tạo và cung cấp nguồn cán bộ kỹ thuật cho ngành Công nghiệp Nhẹ buổi ban đầu.
    
    Ngày đầu thành lập, Trường có trụ sở tại phố Hàng Sũ – thành phố Nam Định, với nhiều khó khăn, thiếu thốn về cơ sở vật chất, phương tiện, kinh nghiệm đào tạo. Tập thể cán bộ giáo viên, học sinh của Trường đã sát cánh cùng nhau vượt qua tất cả. Trường đã hợp tác với các chuyên gia Trung Quốc, Liên Xô, với các cơ sở sản xuất trong nước để xây dựng chương trình, bài giảng, tổ chức đào tạo những khóa học đầu tiên. Ba khoá đầu chỉ với gần 200 học viên ngành Dệt – Sợi, nhưng đó lại là những hạt giống quý, bởi ngay sau khi ra trường, những học viên này đã bắt tay vào việc xây dựng nhiều nhà máy, xí nghiệp đầu tiên của ngành Công nghiệp Dệt Sợi Việt Nam và từ đó, họ đã trưởng thành, nhiều đồng chí đã được giao đảm nhiệm những chức vụ quan trọng của Ngành, của Nhà nước. Khi về làm việc với Trường, nhiều đồng chí lãnh đạo cấp cao của các cơ quan trung ương đều xác định : Đây là một cái nôi đào tạo cán bộ cho ngành Công nghiệp Nhẹ buổi ban đầu.
    
    Từ chuyên ngành Dệt – Sợi, Trường đã mở ra 13 chuyên ngành, gồm : Cơ khí, Lò hơi, Đường, Mỳ chính, Tinh bột, Muối, Giấy, Chế biến gỗ, Kiến trúc, Thiết kế hội hoạ… Quy mô đào tạo đã tăng hơn 500 học sinh/năm. Nhà trường được chuyển đến địa điểm 353 Trần Hưng Đạo và đổi tên thành Trường Trung cấp Kỹ thuật Công nghiệp Nhẹ. Một vinh dự lớn trong thời kỳ này là Trường đã được Bác Hồ chỉ đạo cho mang tên ngoại giao: “Trường Trung cấp Kỹ thuật Sekou Toure” – t­ương xứng với Trường Trung cấp Kỹ thuật Hồ Chí Minh của nước Cộng hoà Ghi Nê Bit Xao, do Tổng thống Sekou Toure đặt tên. Cơ sở vật chất của Trường đã được xây dựng khang trang, đẹp đẽ.
    
    Năm 1965, để phù hợp với tình hình phát triển kinh tế của đất n­ước, sự lớn mạnh của Ngành, cũng như để chống chiến tranh phá hoại của đế quốc Mỹ, leo thang ném bom miền Bắc, Nhà trường đã được tách thành 3 trường:
    
    – Trường Trung học Kỹ thuật Cơ khí vật dụng Hà Bắc;
    
    – Trường Trung học Kỹ thuật Muối Đồ Sơn Hải Phòng;
    
    – Trường Trung học Kỹ thuật Dệt Nam Định.
    
    Năm 1969, giặc Mỹ buộc phải ngừng ném bom miền Bắc, thầy và trò lại trở về Trường tiếp tục nhiệm vụ của mình, phát triển công tác đào tạo, phục vụ kịp thời cho công cuộc khôi phục và phát triển sản xuất của Ngành. Địa bàn tuyển sinh đ­ược mở rộng khắp miền Bắc, không những đào tạo hệ tập trung tại Trường, mà còn phát triển mạnh hệ tại chức, đại học chuyên tu, cung cấp cán bộ kỹ thuật cho các nhà máy trung ương và công nghiệp địa phương, điển hình là chương trình đào tạo phục vụ cơ khí nhỏ cho các tỉnh Nam Định, Hà Nam, Ninh Bình, Thái Bình…
    
    Năm 1971, thực hiện chủ trương vừa nghiên cứu vừa đào tạo, Trường đ­ược nhập với Viện Công nghiệp Dệt Sợi thành Viện Dệt Sekou Toure. Công tác giảng dạy, học tập và nghiên cứu khoa học đó gắn kết với nhau đang trên đà phát triển thì cuối năm 1972, giặc Mỹ lại leo thang đánh phá miền Bắc lần thứ hai, một lần nữa, Trường lại phải đi sơ tán. Bom Mỹ đã tàn phá Trường rất nặng nề, phá hỏng hầu hết nhà xưởng, phòng thí nghiệm và gây thương vong cho nhiều cán bộ, giáo viên. Đầu năm 1973, ngay sau khi Mỹ buộc phải ngừng ném bom miền Bắc lần thứ hai, thầy và trò lại trở về Trường bắt tay vào xây dựng lại từ đống đổ nát. Nhà trường đã nhanh chóng khôi phục, xây dựng lại giảng đường, nhà xưởng, phòng thí nghiệm để tiếp tục giảng dạy, học tập và nghiên cứu khoa học.
    
    Năm 1975, sau khi miền Nam được hoàn toàn giải phóng, đất nước ta hoàn toàn thống nhất. Trước yêu cầu mới là nghiên cứu khoa học và đào tạo phải đáp ứng kịp thời cho cả hai miền, nên Viện Dệt Sekou Toure được tách ra thành Viện Công nghiệp Dệt Sợi và chuyển về Hà Nội (đồng thời thành lập thêm Phân viện tại Tp. Hồ Chí Minh) và Trường Trung học Kỹ thuật Dệt ở lại Nam Định có nhiệm vụ chi viện cán bộ, giáo viên cho các trường phía Nam.
    
    Những năm từ 1975 đến đầu thập kỷ 90 thế kỷ trước là giai đoạn cả nước bước vào thời kỳ khắc phục hậu quả sau chiến tranh. Nền kinh tế n­ước ta bị khủng hoảng nghiêm trọng, đời sống nhân dân vô cùng khó khăn, đã ảnh hưởng lớn đến sự nghiệp giáo dục và đào tạo nói chung và Nhà trường nói riêng. Do mục tiêu đào tạo trung học chuyên nghiệp đứng trước nguy cơ bị phá vỡ do bị thu hẹp, Bộ Công nghiệp Nhẹ đã cho nhập Trường Trung học Giấy Việt Trì, Trường Cán bộ quản lý Bộ Công nghiệp Nhẹ và hệ Trung học May ở Trường May Dâu Keo (Gia Lâm) về Trường, với tên chung là Trường Kỹ thuật Công nghiệp Nhẹ Nam Định và sau đó vào năm 1991, đ­ược đổi tên thành Trường Kinh tế – Kỹ thuật Công nghiệp Nhẹ Nam Định.
    
    Trong thời kỳ đặc biệt khó khăn này, Đảng uỷ và Ban Giám hiệu Nhà trường đã tập trung chỉ đạo khơi dậy tính tự lập tự cường, phát huy cao độ trí tuệ và tài năng của cán bộ, giáo viên, công nhân viên chức và học sinh sinh viên, nhằm tìm ra các giải pháp khắc phục khó khăn để ổn định đời sống và nghiên cứu đổi mới mục tiêu phát triển Nhà trường. Nhiều hoạt động sáng tạo đã được tiến hành rất sôi động, điển hình là phong trào “Đào tạo kết hợp”. Các ch­ương trình đào tạo của Nhà trường gắn với sản xuất tại xưởng trường và các nhà máy, xí nghiệp trong Ngành. Hàng vạn sản phẩm đ­ược cung cấp ra thị trường mang lại hiệu quả kinh tế cao đã góp phần cải thiện đời sống của cán bộ giáo viên và học sinh, đồng thời nâng cao chất lượng đào tạo của Nhà trường. Địa bàn đào tạo của Trường được mở rộng đến các tỉnh Thừa Thiên – Huế, Đà Nẵng, Quảng Nam, Quảng Ngãi, Bình Định… Nhà trường cũng đã đào tạo cho n­ước bạn Lào và Campuchia trên 200 cán bộ trung cấp kỹ thuật. Trong quá trình đào tạo kết hợp, Nhà trường đã chỉ đạo các bộ môn bám sát yêu cầu của sản xuất để đổi mới nội dung đào tạo, kiên quyết giữ vững và nâng cao chất lượng đào tạo bậc trung học chuyên nghiêp, đồng thời thai nghén những mục tiêu cao hơn, phù hợp với sự phát triển của kinh tế – xã hội. Vì vậy, Trường vẫn phát triển bền vững trong bối cảnh mà có nhiều trường trung cấp chuyên nghiệp phải giải thể hoặc xuống đào tạo nghề.
    
    Có thể nói, giai đoạn này là giai đoạn tạo lập văn hóa truyền thống của Nhà trường, đó là: kiên định mục tiêu, đoàn kết sáng tạo, dám nghĩ dám làm, ý chí tiến công cách mạng, vươn lên không mệt mỏi, luôn luôn đi đầu và đổi mới, giữ vững kỷ cương nề nếp, đạo đức người thày. Do đó, Trường luôn đạt nhiều thành tích, là lá cờ đầu trong giáo dục chuyên nghiệp của ngành Công nghiệp Nhẹ và tỉnh Hà Nam Ninh.
    
    GIAI ĐOẠN 2
    
    Đào tạo cao đẳng kinh tế – kỹ thuật
    
    Năm 1992, để phù hợp với công cuộc đổi mới, Bộ Công nghiệp Nhẹ tiếp tục sáp nhập Trường Công nhân Kỹ thuật Công nghiệp Nhẹ Hà Nội (trước đó là Trường Công nhân thuộc Nhà máy Dệt 8/3) với Trường Kinh tế – Kỹ thuật Công nghiệp Nhẹ Nam Định, lấy tên là Trường Kinh tế – Kỹ thuật Công nghiệp Nhẹ. Từ đây, Trường có 2 cơ sở: 456 Minh Khai – Hà Nội và 353 Trần H­ưng Đạo – Nam Định.
    
    Đây là thời kỳ đổi mới sâu rộng của kinh tế – xã hội. Đất nước bước vào thực hiện sự nghiệp CNH, HĐH, xây dựng nền kinh tế thị trường định hướng XHCN. Điều này đòi hỏi giáo dục, đào tạo phải đổi mới để đáp ứng yêu cầu mới của sản xuất. Nhà trường đã tổ chức đề tài nghiên cứu khoa học cầp bộ “KTVCC/93”, phối hợp với Viện Nghiên cứu Phát triển Giáo dục, Vụ Đại học, Vụ THCN – Bộ Giáo dục & Đào tạo tiến hành nghiên cứu các mô hình đào tạo của các nước Pháp, Đức, Thái Lan và một số n­ước khác, cũng như đòi hỏi của thực tế sản xuất trên phạm vi cả nước, đưa ra loại hình cán bộ “miệng nói tay làm” và đề xuất với Nhà n­ước cho phép tổ chức đào tạo thí điểm hệ “Kỹ thuật viên cấp cao”, sau này gọi là “Cử nhân cao đẳng kỹ thuật” và tổ chức đào tạo thí điểm trên diện rộng ở cả ba miền Bắc – Trung – Nam, trên cơ sở liên kết với nhiều trường và các doanh nghiệp trong cả nước.
    
    Kết quả nghiên cứu và kiểm nghiệm cho thấy, học sinh khóa I hệ cao đẳng ra trường về công tác tại các nhà máy, xí nghiệp được khẳng định là phù hợp với yêu cầu sản xuất. Trên cơ sở đó, ngày 24/7/1996, Thủ tướng Chính phủ đã có quyết định số 478/QĐ-TTg nâng cấp Trường thành Trường Cao đẳng Kinh tế – Kỹ thuật Công nghiệp Nhẹ, có nhiệm vụ đào tạo và bồi d­ưỡng cán bộ trình độ cao đẳng, nghiên cứu khoa học phục vụ yêu cầu phát triển kinh tế – xã hội, đào tạo đa cấp, đa ngành.
    
    Năm 1998, Trường được đổi tên thành Trường Cao đẳng Kinh tế – Kỹ thuật Công nghiệp I. Nhà trường đã tập trung mọi lực l­ượng, tiếp tục đa dạng hóa loại hình và mở rộng quy mô đào tạo, thường xuyên đổi mới nội dung chương trình, biên soạn mới các tài liệu, giáo trình. Trường đã triển khai đào tạo các ngành nghề mới, như: Công nghệ thông tin, Điện tự động hoá, Điện tử, Cơ điện tử, Công nghệ ô tô, Tài chính ngân hàng đối với tất cả các bậc đào tạo, các hệ chính quy, vừa học vừa làm và tổ chức đào tạo liên thông giữa các bậc học.
    
    Nhằm xây dựng và tăng cường bồi dưỡng đội ngũ cán bộ quản lý, giảng viên, Đảng uỷ Nhà trường đã có Nghị quyết riêng về công tác cán bộ, tiến hành xây dựng chiến lược và lộ trình phát triển đội ngũ đến năm 2015. Các giải pháp chủ yếu của công tác này là tuyển sinh viên tốt nghiệp loại khá trở lên của các trường đại học có uy tín, tổ chức kèm cặp và thử thách trong một thời gian để xác định năng lực thực tế và mức độ tâm huyết với nghề, sau đó lựa chọn và tạo mọi điều kiện cho họ đi bồi dưỡng nâng cao trình độ về mọi mặt.
    
    Chú trọng và đẩy mạnh công tác nghiên cứu khoa học, coi đó là một nhiệm vụ chính của Nhà trường, Hội đồng Khoa học của Nhà trường được thành lập và nhanh chóng tổ chức triển khai hoạt động. Kết quả trong 11 năm, đã hoàn thành 14 đề tài cấp Bộ, 175 đề tài cấp trường và cấp khoa, không những ứng dụng có hiệu quả trong công tác đào tạo của Nhà trường, mà còn được ứng dụng cho sản xuất tại một số địa ph­ương. Điển hình là các đề tài: Xây dựng ch­ương trình đào tạo liên thông; Công nghiệp hóa nông nghiệp nông thôn; Tin học hóa quản lý nhà trường… Đặc biệt, có một số đề tài do sinh viên làm chủ nhiệm, tiêu biểu là đề tài “Ứng dụng vi điều khiển dòng họ AT89 để điều khiển cơ cấu tự động cuốn dây phơi” của sinh viên Nguyễn Mạnh Trường – lớp Cao đẳng Điện tử K13 đã được nghiệm thu xuất sắc.
    
    Ngay trong thời kỳ này, Nhà trường đã ý thức được hội nhập quốc tế và khu vực là việc làm cần thiết, do đó đã chú ý đẩy mạnh và tăng cường các hoạt động hợp tác quốc tế, liên kết đào tạo với các trường và các tổ chức n­ước ngoài, như: Học viện Công nghệ Rajamangala (RIT) của Thái Lan, Trung tâm Đào tạo IHK Dresden của CHLB Đức, các Tổ chức AOTS, JODC của Nhật Bản, Trường Đại học Kinh tế tài chính Vân Nam – Trung Quốc… nhằm cập nhật và chuyển giao công nghệ mới, đẩy mạnh nghiên cứu khoa học, bồi d­ưỡng đội ngũ, cũng như khai thác mọi nguồn lực để tăng cường cơ sở vật chất và hiện đại hóa các ph­ương tiện, thiết bị dạy học.
    
    Nhà trường đã thực hiện tốt mục tiêu gắn đào tạo với thực tế sản xuất bằng hoạt động liên kết với các doanh nghiệp và các viện nghiên cứu, như:­ Công ty Dệt Nam Định, Công ty Dệt Huế, Công ty Dệt Nha Trang, Công ty Dệt Hà Nội, Công ty Dệt 8/3, Công ty Bia Hà Nội, Công ty Bia Na Đa, Công ty May Nam Định, Công ty May xuất khẩu Nam Định, Công ty May 10, Công ty Cơ khí Thăng Long, Viện Dệt May, Công ty Giấy Bãi Bằng, Viện Giấy và Xenluylo, Viện Công nghiệp thực phẩm… để sử dụng những thiết bị mới, công nghệ và tổ chức quản lý sản xuất tiên tiến phục vụ cho thực hành và thí nghiệm của sinh viên.
    
    Để công tác quản lý chất lượng đào tạo đạt kết quả cao, Nhà trường đã đưa ra các biện pháp, những quy định cụ thể về tiêu chuẩn hóa những nội dung đào tạo và quy trình xét duyệt đối với giáo viên tham gia thỉnh giảng; tổ chức thi và kiểm tra theo ngân hàng đề thi; tiến hành thanh tra trước khi bắt đầu mỗi kỳ thi; tổ chức thi lý thuyết “3 chung” đối với tất cả các môn học; thi thực hành đ­ược gắn với sản phẩm đưa ra thị trường… Đẩy mạnh công tác quản lý HSSV, tổ chức các đợt sinh hoạt giáo dục và phân loại định kỳ, th­ường xuyên liên hệ với các gia đình thông qua hệ thống mạng, để thông báo tình hình và phối hợp quản lý, đồng thời tổ chức các hoạt động phong trào nhằm thu hút để đào tạo toàn diện đối với HSSV. Kết quả khảo sát cho thấy, trên 85% học sinh tốt nghiệp ra trường đã có việc làm và được các cơ quan, doanh nghiệp tiếp nhận đánh giá cao.
    
    Đồng bộ với các giải pháp trên, Nhà trường đã tăng cường đầu tư cơ sở vật chất. Trong khoảng thời gian 10 năm, Trường đã cải tạo, nâng cấp và xây dựng mới được nhiều nhà xưởng, như: Các giảng đ­ường C, D, K; x­ưởng thực hành 3 tầng; nhà làm việc 9 tầng tại cơ sở Hà Nội; giảng đ­ường A1; nhà ăn; nhà làm việc của giáo viên; nhà Hành chính A5 tại cơ sở Nam Định… đã tạo được cảnh quan môi trường ở cả 2 cơ sở khang trang, sạch đẹp. Trường cũng tiến hành mua sắm thêm nhiều trang thiết bị hiện đại, nh­ư: Hệ thống máy CNC cho ngành Cơ khí, máy thiết kế mẫu và giác sơ đồ tự động cho ngành May, hệ thống máy may chuyên dụng điều khiển bằng điện tử của Nhật Bản, máy so màu quang phổ và thí nghiệm nhuộm mẫu nhỏ cho ngành Nhuộm, đặc biệt là xây dựng hai hệ thống th­ư viện, trong đó có thư viện điện tử, hệ thống phòng họp cầu truyền hình trực tuyến giữa hai cơ sở… đáp ứng cơ bản yêu cầu đào tạo của Trường trong giai đoạn mới.
    
    Bên cạnh đó, Nhà trường đã tập trung chỉ đạo phát triển các hoạt động thực tập kết hợp với lao động sản xuất và tăng cường dịch vụ đào tạo trong khuôn khổ cho phép để tăng thêm nguồn thu phúc lợi cũng như tạo nhiều việc làm cho cán bộ giáo viên, đưa mức thu nhập bình quân liên tục năm sau cao hơn năm trước.
    
    Nhà trường cũng thường xuyên tổ chức tham quan vào các dịp nghỉ hè, tết, ngày lễ cho cán bộ, giáo viên và chăm lo cải thiện điều kiện ăn ở, sinh hoạt cho học sinh sinh viên khu nội trú, đồng thời chỉ đạo và tạo điều kiện cho Công đoàn và Đoàn Thanh niên tăng cường các hoạt động văn hóa thể thao lành mạnh cũng nh­ư các hoạt động giao l­ưu trong học sinh sinh viên giữa 2 cơ sở và các đơn vị liên kết dưới các hình thức thi đấu thể thao, biểu diễn văn nghệ, cắm trại và tham gia các cuộc thi tìm hiểu do Đài Truyền hình Việt Nam tổ chức… Các hoạt động trên đã thực sự tạo nên không khí đoàn kết, phấn khởi và yên tâm công tác trong Nhà trường.
    
    Đánh giá kết quả 11 năm đào tạo cao đẳng của Nhà trường, chúng ta có thể vui mừng nhận thấy: Đấy là thời kỳ phát triển mới của Nhà trường sau 40 năm vững vàng đào tạo trung cấp chuyên nghiệp; Cũng là thời kỳ thể hiện và phát huy văn hóa truyền thống, là thời kỳ có tốc độ phát triển nhanh nhưng chắc chắn và bền vững, tạo nền tảng đáp ứng cho giai đoạn đào tạo đại học sau này.
    
    GIAI ĐOẠN 3
    
    Khởi đầu của sự nghiệp đào tạo đại học
    
    Công tác chuẩn bị để thành lập Trường Đại học Kinh tế – Kỹ thuật Công nghiệp hôm nay đã đ­ược tiến hành từ rất sớm. Ngay khi còn là trường trung cấp, Nhà trường đã hợp tác với các trường Đại học Bách khoa Hà Nội, Đại học Kinh tế Quốc dân, Đại học Kỹ thuật Công nghiệp Thái Nguyên… để mở các lớp đào tạo đại học tại chức từ năm 1964, các lớp đại học chuyên tu thực hành từ năm 1983, các lớp đại học bằng 2 về quản trị kinh doanh cho cán bộ quản lý từ năm 1992, các lớp cao học từ năm 1997… Thông qua các ch­ương trình đào tạo liên kết với các trường đại học, Nhà trường đã tổ chức nghiên cứu để xây dựng các ch­ương trình đào tạo đại học cho các ngành học của Trường, trên cơ sở chương trình khung của Bộ Giáo dục & Đào tạo quy định và theo hướng tiếp cận công nghệ mới, đồng thời tạo điều kiện cho giảng viên của Trường làm quen với công tác giảng dạy đại học.
    
    Song song với quá trình chuẩn bị nội dung, ch­ương trình đào tạo bậc đại học, đội ngũ giáo viên cũng đ­ược tăng cường tuyển mới, phân loại và tổ chức bồi dưỡng liên tục. Nhà trường đã tích cực mở các lớp bồi dưỡng sư phạm và các lớp chuyên đề về công nghệ mới tại Trường, cũng như tìm nguồn để cử giáo viên đi học tập bồi d­ưỡng ở nước ngoài. Hàng năm có từ 15 đến 20 giáo viên được đi bồi dưỡng ở các nước: Đức, Nhật Bản, Hàn Quốc, Singapore, Malaisia, Thái Lan, Trung Quốc, Brunây… Đồng thời đã tổ chức thường xuyên các hội giảng cấp khoa, cấp trường và tham gia tích cực hội giảng cấp tỉnh, thành phố và toàn quốc. Các kỳ hội giảng đó đã giúp cho giáo viên và Nhà trường nhiều kinh nghiệm để đổi mới ph­ương pháp giảng dạy, nhiều giáo viên đã đạt được giải cao.
    
    Căn cứ vào khả năng thực tế của Nhà trường và nhu cầu đào tạo nguồn nhân lực có trình độ đại học công nghệ, có tư duy khoa học và kỹ năng nghề cao, đáp ứng yêu cầu CNH, HĐH đất n­ước, đặc biệt là khu vực đồng bằng Sông Hồng, Nhà trường đã được Bộ Công nghiệp đưa vào diện quy hoạch nâng cấp thành trường đại học giai đoạn 2004 – 2010. Thực hiện chỉ đạo của Bộ, năm 2005, Nhà trường đã tiến hành xây dựng Đề án thành lập Trường Đại học Kinh tế – Kỹ thuật Công nghiệp trên cơ sở Trường Cao đẳng Kinh tế – Kỹ thuật Công nghiệp I.
    
    Qúa trình xây dựng đề án, Nhà trường đã đ­ược Bộ Công nghiệp (nay là Bộ Công Thương), Bộ Giáo dục & Đào tạo, UBND tỉnh Nam Định và các bộ, ban, ngành của trung ương và địa ph­ương đặc biệt quan tâm tạo mọi điều kiện về cấp đất mở rộng mặt bằng, đầu t­ư nâng cấp cơ sở vật chất và đội ngũ, nhanh chóng tổ chức thẩm định và trình Chính phủ ra Quyết định. Kết quả là: Ngày 11/9/2007, Thủ tướng Chính phủ đã ký Quyết định số 1206/QĐ-TTg thành lập Trường Đại học Kinh tế – Kỹ thuật Công nghiệp trên cơ sở nâng cấp Trường Cao đẳng Kinh tế – Kỹ thuật Công nghiệp I.
    
    Ngay sau khi có Quyết định của Thủ tướng Chính phủ, Nhà trường đã khẩn trương triển khai các thủ tục pháp lý cần thiết và đã đ­ược Bộ Giáo dục & Đào tạo cho phép mở 5 ngành đào tạo đại học, gồm: Công nghệ Dệt, Công nghệ Thực phẩm, Công nghệ Kỹ thuật Điện, Kế tóan và Quản trị kinh doanh, với chỉ tiêu 700 SV khóa 1. Đến hôm nay, các em đã tốt nghiệp, trở thành các kỹ s­ư và cử nhân đại học.
    
    Từ sau khi được nâng cấp thành trường đại học, lãnh đạo Trường và toàn thể cán bộ, giáo viên và HSSV đã thể hiện rõ ý chí và quyết tâm vươn lên mạnh mẽ trong bối cảnh đất nước bước vào hội nhập quốc tế. Kết quả đạt được trong thời gian 4 năm vừa qua của Nhà trường là một sự tiếp nối mạnh mẽ truyền thống và những thành tựu của hơn 50 năm trước. Đó là:
    
    – Nhà trường tiếp tục đào tạo đa cấp; đa ngành với số l­ượng 10 ngành đại học, 15 ngành cao đẳng và 15 ngành trung cấp chuyên nghiệp. Th­ương hiệu của Nhà trường luôn được giữ vững và quy mô đào tạo ngày càng tăng cao, thể hiện rất rõ qua các kỳ tuyển sinh với số lượng thí sinh dự tuyển hàng năm rất đông, kết quả tuyển sinh luôn đạt và vượt chỉ tiêu trong phạm vi cho phép và đến nay nguồn tuyển sinh vẫn đang rất dồi dào.
    
    – Mặt bằng đất sử dụng của Nhà trường đã được mở rộng rất lớn: Tại cơ sở Nam Định có 2 địa điểm gồm 17.000m2 ở 353 Trần Hưng Đạo và 250.000m2 tại phường Mỹ Xá (trong đó 200.000m2 chính thức và 50.000m2 tạm giao). Tại cơ sở Hà Nội cũng có 2 địa điểm gồm 7.000m2 ở 456 Minh Khai, quận Hai Bà Trưng và 20.000m2 tại phường Lĩnh Nam, quận Hoàng Mai đã dược Thành phố Hà Nội cấp phép xây dựng.
    
    Trong 5 năm qua, Nhà trường đã tiếp tục triển khai dự án “Quy hoạch tổng thể Trường Đại học Kinh tế – Kỹ thuật đến năm 2020”, với tổng mức đầu t­ư trên 550 tỷ đồng. Đến nay đã thực hiện xây cơ bản xong nhà 15 tầng (cao nhất thành phố Nam Định hiện nay), 3 xưởng thực hành với diện tích trên 3.000m2; 2 nhà ký túc xá và hệ thống hạ tầng tại cơ sở tại Mỹ Xá, hệ thống sân vườn, cảnh quan của cả 2 cơ sở Hà Nội và Nam Định với mức thực hiện trên 250 tỷ đồng (trong đó 80% là vốn tự có của Trường). Đồng thời đã đầu tư mua sắm thêm trang thiết bị trên 70 tỷ đồng.
    
    Công tác bồi dưỡng, phát triển đội ngũ trong thời gian này cũng tiếp tục được tăng cường rất mạnh.
    
    – Đến nay, trường đã có 660 cán bộ giáo viên cơ hữu, trong đó có 540 giảng viên với 72 tiến sĩ và nghiên cứu sinh; 360 thạc sĩ và cao học, chiếm tỷ lệ gần 80% giáo viên cơ hữu. Ngoài ra, cũng có gần 300 PGS, TS, ThS và kỹ sư có kinh nghiệm của các trường đại học, các viện và doanh nghiệp tham gia thỉnh giảng.
    
    – Công tác nghiên cứu khoa học đã được đưa vào định mức cho từng giảng viên, Hội đồng khoa học của Nhà trường đ­ược kiện toàn và hoạt động theo quy chế mới của trường đại học. Kết quả trong 5 năm qua đã hoàn thành 12 đề tài cấp Bộ, 17 chương trình khung và tiêu chuẩn kỹ năng nghề cấp Tổng cục Dạy nghề, 255 đề tài cấp trường và cấp khoa, ứng dụng có hiệu quả trong công tác của Nhà trường và cho sản xuất tại một số địa phương.
    
    – Công tác quản lý học sinh sinh viên đ­ược tách ra từ phòng Tổ chức Cán bộ – Học sinh sinh viên thành một phòng riêng biệt, tăng cường thêm cán bộ, phương tiện và tổ chức các hoạt động theo chiều sâu, kết hợp chặt chẽ với công an, chính quyền địa phương và gia đình đảm bảo nắm chắc tình hình học sinh sinh viên cả trong trường và ngoài xã hội; giữ vững an ninh trật tự nhà trường và địa bàn, không để xảy ra những vụ việc lớn. Đồng thời Nhà trường đã tăng cường các hoạt động văn hóa, thể thao và giao lưu giữa 2 cơ sở, với địa ph­ương và các cơ quan khác; Tổ chức nhiều hội thi, nói chuyện chuyên đề gắn với nghiên cứu khoa học; Thường xuyên tổ chức thi học sinh giỏi các chuyên ngành; Chăm lo, đầu tư và huấn luyện cho các em sinh viên giỏi tham dự thi tay nghề các cấp. Kết quả hàng năm đều có học sinh đạt giải cao cấp quốc gia và khu vực, đặc biệt năm 2011, em Vũ Thị Mai Hiên – lớp Đại học liên thông May K3 đã đạt Huy chương Vàng, đứng thứ nhất Đông Nam Á nghề May – Thời trang, là 01 trong 13 thí sinh xuất sắc đại diện cho 12 nghề của Việt Nam được cử đi dự thi tay nghề quốc tế tại thủ đô Luân Đôn nước Anh và là 1 trong 7 em đạt chứng chỉ xuất sắc của Đoàn Việt Nam tại kỳ thi Quốc tế năm 2011.
    
    – Về hợp tác quốc tế trong những năm gần đây, Nhà trường tiếp tục đưa mối quan hệ với các đối tác hiện có đi vào chiều sâu và mở rộng với các đối tác mới, như: Trường Đại học Western Sydney của Australia, Trường Đại học Khoa học và Công nghệ của Đài Loan; Trường Đại học quốc gia Lào, Trường Đại học Công nghệ thực phẩm Plovdiv của Bulgaria… Đặc biệt, ngày 14/10/2011, Nhà trường đã tham gia và là thành viên chính thức của Hiệp hội Quốc tế các trường đại học về Khoa học và Công nghệ thực phẩm có trụ sở đặt tại Plovdiv Bulgaria, gồm 18 trường đại học từ các nước Pháp, Đức; Nga, Thổ Nhĩ Kỳ, Hy Lạp, Bulgaria;… với mục đích hợp tác và trao đổi về nghiên cứu khoa học, hỗ trợ lẫn nhau về các chương trình đào tạo tiên tiến và hướng vào việc mở các lớp chất lượng cao trên tinh thần hợp tác đôi bên cùng có lợi.
    
    – Về chăm lo cải thiện đời sống cho cán bộ giáo viên và học sinh sinh viên, Nhà trường tiếp tục tập trung chỉ đạo phát triển các hoạt động thực tập kết hợp với lao động sản xuất và tăng cường dịch vụ đào tạo để tăng thêm nguồn thu phúc lợi cũng như tạo thêm việc làm cho cán bộ giáo viên. Bổ sung và ban hành mới “Quy chế chi tiêu nội bộ” sát với Nghị định 43/CP và các quy định mới của Nhà n­ước trên tinh thần công khai từ cơ sở tổ, bộ môn và các phòng, khoa; Đảm bảo phát huy cao độ tính công bằng và dân chủ cho mọi người. Kết quả đã đưa mức thu nhập bình quân hiện nay đạt 6.500.000 đồng/người/tháng. Các hoạt động xã hội và văn hóa văn nghệ tiếp tục đ­ược duy trì, đẩy mạnh, tạo nên không khí vui tươi, phấn khởi, trong cán bộ, giáo viên, học sinh sinh viên.
    
     
    
    Nhìn lại chặng đường phấn đấu hơn nửa thế kỷ qua, chắc chắn mỗi cán bộ, giáo viên, công nhân viên chức và học sinh, sinh viên của Nhà trường sẽ cảm thấy rất hạnh phúc và tự hào vì đã phấn đấu bền bỉ, cống hiến hết sức mình cho sự tồn tại và phát triển của Nhà trường, giữ vững uy tín và danh tiếng của một ngôi trường với 40 năm liên tục, vững vàng là trường trung học chuyên nghiệp hàng đầu trong khối giáo dục chuyên nghiệp; 11 năm là trường cao đẳng mạnh của Bộ Công Thương và hôm nay đang bắt đầu một giai đoạn mới đào tạo ở bậc đại học. Là nơi đã đào tạo cho đất nước trên 140.000 cán bộ trình độ đại học, cao đẳng và trung học chuyên nghiệp có chất lượng cao và đã trở thành một địa chỉ đào tạo có uy tín trong cả nước, có quy mô đào tạo ngày càng tăng, số lượng thí sinh đăng ký dự thi vào trường hàng năm cũng liên tục tăng lên. Kết quả tuyển sinh luôn luôn đạt và vượt chỉ tiêu. Quy mô của Trường hiện nay đã đạt trên 30.000 học sinh sinh viên.
    
    Với những thành tích trên đây, chúng ta có thể tự hào và khẳng định rằng: Trường Đại học Kinh tế – Kỹ thuật Công nghiệp đã có quá trình 55 năm phát triển bền vững, nay đang vươn ra biển lớn để hội nhập toàn cầu.
    
    Những thành quả trên là công sức của cả tập thể Đảng uỷ, Lãnh đạo nhà trường, các tổ chức đoàn thể quần chúng: Công đoàn, Đoàn Thanh niên Cộng sản Hồ Chí Minh, Hội Phụ nữ, Hội Cựu chiến binh… và của toàn thể cán bộ, giáo viên, công nhân viên và học sinh sinh viên. Điều này đã được Đảng, Nhà nước và các cấp bộ, ngành ghi nhận và tặng th­ưởng nhiều phần thưởng cao quý.
    
    Nhà trường đã được tặng thưởng: 02 Huân chương Độc lập hạng Nhất (2011; 2005), 01 hạng Nhì (2001), 01 hạng Ba (1996), 2 Huân chương Lao động hạng Nhất (1985, 1992) 01 hạng Nhì (1981) và 02 hạng Ba (1960, 1962). Huân chương Tự do hạng Nhất của nước Cộng hoà Dân chủ Nhân dân Lào (1981) và rất nhiều cờ thưởng, bằng khen của các cấp, các ngành…
    
    Công đoàn Trường đã được tặng th­ưởng Huân chương Lao động hạng Ba (2005).
    
    Đoàn Thanh niên được tặng thưởng Huân chương Lao động hạng Nhì (2004) và hạng Ba (1999).
    
    01 cá nhân được tăng th­ưởng Huân chương Lao động hạng Nhất, hạng Nhì và hạng Ba; 04 cá nhân đ­ược tặng thưởng Huân chương Lao động hạng Ba; 682 cán bộ giáo viên được tặng thưởng các loại Huân, Huy chương khác; 02 thầy giáo được phong tặng danh hiệu Nhà giáo Nhân dân, 13 thầy cô giáo được phong tặng danh hiệu Nhà giáo ­Ưu tú; 27 phòng, ban, khoa và cá nhân được tặng bằng khen của Thủ t­ướng Chính phủ…
    
    Những thành tích trên của Nhà trường là rất vẻ vang, được xây dựng lên từ những truyền thống và có nguyên nhân sâu xa, rất đặc trưng, được coi là những kinh nghiệm rất quý báu. Trước tiên là truyền thống đoàn kết, thuỷ chung, trên d­ưới một lòng, cơ quan hoà thuận, giữ gìn ý thức tổ chức kỷ luật, đảm bảo dân chủ nội bộ và chia sẻ cùng nhau những lúc vui buồn, nh­ư một đại gia đình ấm áp tình thương. Đó là yếu tố quan trọng nhất cho sự phát triển nhà trường cần phải được chăm lo giữ gìn “nh­ư giữ gìn con ngươi của mắt mình” mà Chủ tịch Hồ Chí Minh đã dạy.
    
    Những bài học quý cũng đ­ược rút ra từ sự chỉ đạo về tập trung trí tuệ, tìm tòi, vận dụng sáng tạo những quan điểm, đường lối của Đảng và Nhà nước vào công tác đào tạo. Động viên toàn thể các lực l­ượng với tinh thần luôn sẵn sàng và vươn tới nhận nhiệm vụ ở mức cao hơn, hết lòng vì học sinh thân yêu, gắn bó và quyết tâm xây dựng Nhà trường với tất cả tâm huyết của mình. Đây chính là yếu tố quyết định giúp cho Nhà trường đào tạo cho đất nước, cho ngành hàng vạn sản phẩm quý, đó là đội ngũ những ng­ười thợ giỏi, những cán bộ kỹ thuật và những nhà quản lý đã và đang công tác ở nhiều nhà máy, xí nghiệp trên khắp mọi miền của Tổ quốc.
    
    Nói đến truyền thống và những thành tích trên đây của Nhà trường, không thể tách rời sự chỉ đạo và tạo điều kiện hết sức quý báu của Đảng và Nhà nước, của Bộ Công Thương, Bộ Giáo dục & Đào tạo, của tỉnh Nam Định; thành phố Hà Nội; của các sở ban ngành, thành phố Nam Định, quận Hai Bà Trưng, của các cơ quan, các doanh nghiệp, các trường bạn và tất cả các đơn vị có mối quan hệ giúp đỡ Trường trong những năm qua.
    
    Những thành tích và kinh nghiệm xây dựng Nhà trường trong hơn nửa thế kỷ qua không chỉ là niềm tự hào của các thế hệ chúng ta hôm nay, mà cũng là nền tảng tạo đà cho các thế hệ mai sau tiếp tục phát huy.
    
    Lãnh đạo và toàn thể cán bộ, giáo viên, công nhân viên và học sinh, sinh viên Nhà trường tuy đã cố gắng và đạt nhiều thành tích tốt đẹp, song cũng còn không ít những khó khăn, nhược điểm cần phải khắc phục và quyết tâm phấn đấu để xây dựng Nhà trường trở thành trường đại học chuẩn, với uy tín và đẳng cấp quốc tế trong tương lai. Nhiệm vụ trước mắt là tiếp tục sắp xếp tổ chức bộ máy đáp ứng với yêu cầu nhiệm vụ mới, triển khai đồng bộ các giải pháp nâng cao chất lượng đào tạo ở các bậc học; Thực hiện nghiêm túc cuộc vận động: “Học tập và làm theo tấm gương đạo đức Hồ Chí Minh”; Kiên quyết “Nói không với tiêu cực và bệnh thành tích trong giáo dục”, “Nói không với vi phạm đạo đức nhà giáo và ngồi nhầm lớp” và “Nói không với đào tạo không đạt chuẩn”; Khẩn trương triển khai và hoàn thành vượt mức kế hoạch của Dự án Quy hoạch tổng thể Nhà trường đến năm 2020, đặc biệt là dự án mở rộng cở sở Hà Nội của Trường tại phường Lĩnh Nam – quận Hoàng Mai; Tiếp tục đổi mới nội dung chương trình đào tạo; Bổ sung nâng cấp cơ sở vật chất, đặc biệt là thiết bị thí nghiệm hiện đại và xây dựng đội ngũ giảng viên ngang tầm nhiệm vụ mới. Đây cũng chính là mục tiêu và phương hướng hành động mà tất cả cán bộ, giáo viên, công nhân viên chức và học sinh, sinh viên Nhà trường sẽ phải quyết tâm thực hiện trong thời gian tới.
    
    Phát huy truyền thống đạt được 60 năm qua, xác định rõ định hướng và mục tiêu nhiệm vụ trong thời gian tới, chắc chắn, Trường Đại học Kinh tế – Kỹ thuật Công nghiệp sẽ tiếp tục phát triển bền vững, đóng góp nhiều hơn nữa trong việc đào tạo nguồn nhân lực chất lượng cao cho sự nghiệp CNH, HĐH đất nước và hội nhập quốc tế.`
}